# Generated by Django 6.0.3 on 2026-04-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrdering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emial',
            new_name='email',
        ),
    ]
