# Generated by Django 6.0.3 on 2026-04-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrdering', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('order_cancelled_by_user', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_find_status', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.user')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, null=True)),
                ('payment_mode', models.CharField(choices=[('cod', 'cash on delivery'), ('online', 'online payment')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(max_length=20, null=True)),
                ('cvv', models.CharField(max_length=5, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1)),
                ('comm', models.TextField(null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.user')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.user')),
            ],
        ),
    ]
