# Generated by Django 6.0.3 on 2026-04-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOrdering', '0005_foodtracking_orderaddress_paymentdetails_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='order_find_status',
            new_name='order_final_status',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_food_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodOrdering.food'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'food')},
        ),
    ]
